# -*- coding: utf-8 -*-
"""self_pruning_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c69b7isFWQyloZghdn1OVUvfMp5STpS1
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np



# Part 1: PrunableLinear Layer  (fixed)

class PrunableLinear(nn.Module):
    """
    Linear layer with per-weight learnable gates.

    forward:
        gates         = sigmoid(gate_scores)        ∈ (0, 1)
        pruned_weight = weight ⊙ gates
        output        = x @ pruned_weight.T + bias

    FIX vs v1:
        gate_scores initialised to 0.0  →  sigmoid(0) = 0.5
        This puts gates in the steepest part of the sigmoid where
        gradients are largest, making L1 pressure effective immediately.
        (v1 used 2.0 → sigmoid ≈ 0.88, very hard to push to 0)
    """

    def __init__(self, in_features: int, out_features: int, bias: bool = True):
        super().__init__()
        self.in_features  = in_features
        self.out_features = out_features

        self.weight      = nn.Parameter(torch.empty(out_features, in_features))
        self.bias        = nn.Parameter(torch.zeros(out_features)) if bias else None

        # KEY FIX: init at 0 not 2 → sigmoid(0)=0.5, maximum gradient region
        self.gate_scores = nn.Parameter(torch.zeros(out_features, in_features))

        nn.init.kaiming_uniform_(self.weight, a=0.01)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        gates         = torch.sigmoid(self.gate_scores)   # (out, in)
        pruned_weight = self.weight * gates
        return F.linear(x, pruned_weight, self.bias)

    # ── helpers ───────────────────────────────────────────────────────────────

    def get_gates(self) -> torch.Tensor:
        return torch.sigmoid(self.gate_scores).detach().cpu()

    def sparsity_fraction(self, threshold: float = 1e-2) -> float:
        return (self.get_gates() < threshold).float().mean().item()

    def extra_repr(self) -> str:
        return f"in={self.in_features}, out={self.out_features}"



# Part 2: Network — CNN backbone + prunable classifier head

class SelfPruningCNN(nn.Module):
    """
    Architecture
    ────────────
    CNN Backbone (standard conv layers, NOT pruned):
        Conv(3→64)  → BN → ReLU → MaxPool
        Conv(64→128)→ BN → ReLU → MaxPool
        Conv(128→256)→BN → ReLU → MaxPool
        AdaptiveAvgPool → 256-d feature vector

    Prunable Classifier Head:
        PrunableLinear(256 → 512) → BN → ReLU → Dropout
        PrunableLinear(512 → 256) → BN → ReLU → Dropout
        PrunableLinear(256 → 10)

    Why split CNN + prunable head?
        Conv layers are already parameter-efficient.
        The dense classifier is where redundancy lives — pruning it
        gives meaningful sparsity without destroying feature extraction.
    """

    def __init__(self, dropout: float = 0.4):
        super().__init__()

        # CNN backbone
        def conv_block(in_ch, out_ch):
            return nn.Sequential(
                nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1, bias=False),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
                nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1, bias=False),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
                nn.MaxPool2d(2),
            )

        self.backbone = nn.Sequential(
            conv_block(3,   64),   # 32→16
            conv_block(64,  128),  # 16→8
            conv_block(128, 256),  # 8→4
            nn.AdaptiveAvgPool2d(1),  # 4→1  →  256-d vector
            nn.Flatten(),
        )

        # Prunable classifier head
        self.head = nn.Sequential(
            PrunableLinear(256, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),

            PrunableLinear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),

            PrunableLinear(256, 10),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        features = self.backbone(x)
        return self.head(features)

    # ── Gate / sparsity helpers ───────────────────────────────────────────────

    def prunable_layers(self) -> list[PrunableLinear]:
        return [m for m in self.modules() if isinstance(m, PrunableLinear)]

    def sparsity_loss(self) -> torch.Tensor:
        """Sum of all sigmoid-gate values (L1, since gates ≥ 0)."""
        return torch.cat([
            torch.sigmoid(l.gate_scores).view(-1)
            for l in self.prunable_layers()
        ]).sum()

    def overall_sparsity(self, threshold: float = 1e-2) -> float:
        total = pruned = 0
        for l in self.prunable_layers():
            g = l.get_gates()
            total  += g.numel()
            pruned += (g < threshold).sum().item()
        return 100.0 * pruned / total if total else 0.0

    def all_gate_values(self) -> np.ndarray:
        return np.concatenate([
            l.get_gates().numpy().ravel() for l in self.prunable_layers()
        ])


# ─────────────────────────────────────────────────────────────────────────────
# Data
# ─────────────────────────────────────────────────────────────────────────────

def get_cifar10_loaders(batch_size: int = 128):
    mean = (0.4914, 0.4822, 0.4465)
    std  = (0.2470, 0.2435, 0.2616)

    train_tf = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])
    test_tf = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])

    train_ds = torchvision.datasets.CIFAR10("./data", train=True,  download=True, transform=train_tf)
    test_ds  = torchvision.datasets.CIFAR10("./data", train=False, download=True, transform=test_tf)

    kw = dict(num_workers=2, pin_memory=True)
    return (DataLoader(train_ds, batch_size=batch_size, shuffle=True,  **kw),
            DataLoader(test_ds,  batch_size=batch_size, shuffle=False, **kw))


# ─────────────────────────────────────────────────────────────────────────────
# Training
# ─────────────────────────────────────────────────────────────────────────────

def train_one_epoch(model, loader, optimizer, lambda_sparse, device, warmup: bool):
    """
    warmup=True  → sparsity loss is NOT applied (network learns to classify first).
    warmup=False → full loss = CrossEntropy + λ·SparsityLoss.
    """
    model.train()
    tot_sum = cls_sum = spr_sum = 0.0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()

        logits   = model(images)
        cls_loss = F.cross_entropy(logits, labels)

        if warmup:
            loss     = cls_loss
            spr_loss = torch.tensor(0.0)
        else:
            spr_loss = model.sparsity_loss()
            loss     = cls_loss + lambda_sparse * spr_loss

        loss.backward()
        # Clip gradients to stabilise training
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
        optimizer.step()

        n = images.size(0)
        tot_sum += loss.item()     * n
        cls_sum += cls_loss.item() * n
        spr_sum += spr_loss.item() * n

    N = len(loader.dataset)
    return tot_sum / N, cls_sum / N, spr_sum / N


@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()
    correct = total = 0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        correct += (model(images).argmax(1) == labels).sum().item()
        total   += labels.size(0)
    return 100.0 * correct / total


def build_optimizer(model, lr_main=1e-3, lr_gate=5e-3, wd=1e-4):
    """
    Separate parameter groups:
      • gate_scores  → higher LR so they respond quickly to sparsity pressure
      • everything else → standard LR
    """
    gate_params  = [p for n, p in model.named_parameters() if "gate_scores" in n]
    other_params = [p for n, p in model.named_parameters() if "gate_scores" not in n]
    return optim.Adam([
        {"params": other_params, "lr": lr_main, "weight_decay": wd},
        {"params": gate_params,  "lr": lr_gate, "weight_decay": 0.0},
    ])


def train_and_evaluate(
    lambda_sparse: float,
    train_loader,
    test_loader,
    device,
    num_epochs:   int   = 60,
    warmup_epochs: int  = 10,   # pure classification before sparsity kicks in
    verbose:      bool  = True,
) -> tuple[float, float, SelfPruningCNN]:

    model     = SelfPruningCNN().to(device)
    optimizer = build_optimizer(model)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)

    if verbose:
        n_prunable = sum(l.weight.numel() for l in model.prunable_layers())
        print(f"\n{'='*65}")
        print(f"  λ = {lambda_sparse}  |  Prunable weights: {n_prunable:,}"
              f"  |  Warmup: {warmup_epochs} epochs")
        print(f"{'='*65}")
        print(f"{'Ep':>4}  {'TotLoss':>8}  {'ClsLoss':>8}  "
              f"{'SprLoss':>8}  {'Sparsity':>9}  {'Phase':>8}")
        print("-" * 55)

    for epoch in range(1, num_epochs + 1):
        is_warmup = epoch <= warmup_epochs
        tot, cls, spr = train_one_epoch(
            model, train_loader, optimizer, lambda_sparse, device, warmup=is_warmup)
        scheduler.step()

        if verbose and (epoch % 5 == 0 or epoch == 1):
            sparsity = model.overall_sparsity()
            phase    = "WARMUP" if is_warmup else "PRUNE"
            print(f"{epoch:>4}  {tot:>8.4f}  {cls:>8.4f}  "
                  f"{spr:>8.1f}  {sparsity:>8.1f}%  {phase:>8}")

    test_acc = evaluate(model, test_loader, device)
    sparsity = model.overall_sparsity()

    if verbose:
        print(f"\n  ✔  Test Accuracy : {test_acc:.2f}%")
        print(f"  ✔  Sparsity Level: {sparsity:.1f}%")

    return test_acc, sparsity, model



# Plotting


def plot_gate_distribution(model: SelfPruningCNN, lambda_val: float,
                           save_path: str = "gate_distribution.png"):
    gates    = model.all_gate_values()
    sparsity = model.overall_sparsity()

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Left: full distribution
    axes[0].hist(gates, bins=100, color="#2196F3", edgecolor="white", lw=0.3)
    axes[0].axvline(0.01, color="#F44336", ls="--", lw=1.5, label="Threshold 0.01")
    pct = (gates < 0.01).mean() * 100
    axes[0].set_title(f"All gate values  (λ={lambda_val})", fontsize=12)
    axes[0].set_xlabel("Gate value  σ(score)")
    axes[0].set_ylabel("Count")
    axes[0].text(0.55, 0.92, f"Pruned: {pct:.1f}%\nSparsity: {sparsity:.1f}%",
                 transform=axes[0].transAxes, fontsize=10,
                 bbox=dict(boxstyle="round", fc="lightyellow", alpha=0.9))
    axes[0].legend()

    # Right: zoom into [0, 0.1] to show the spike at 0
    axes[1].hist(gates[gates < 0.1], bins=60, color="#4CAF50", edgecolor="white", lw=0.3)
    axes[1].axvline(0.01, color="#F44336", ls="--", lw=1.5, label="Threshold 0.01")
    axes[1].set_title(f"Zoom: gates < 0.1  (λ={lambda_val})", fontsize=12)
    axes[1].set_xlabel("Gate value")
    axes[1].set_ylabel("Count")
    axes[1].legend()

    plt.suptitle("Self-Pruning Network — Gate Value Distribution", fontsize=13, y=1.01)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    print(f"\n  Plot saved → {save_path}")
    plt.show()


def plot_all_distributions(results, save_path="all_gate_distributions.png"):
    """One subplot per λ value for easy comparison."""
    fig, axes = plt.subplots(1, len(results), figsize=(6 * len(results), 5))
    if len(results) == 1:
        axes = [axes]

    for ax, (lam, acc, sparsity, model) in zip(axes, results):
        gates = model.all_gate_values()
        ax.hist(gates, bins=80, color="#2196F3", edgecolor="white", lw=0.2)
        ax.axvline(0.01, color="#F44336", ls="--", lw=1.2)
        ax.set_title(f"λ = {lam:.0e}\nAcc={acc:.1f}%  Sparse={sparsity:.1f}%", fontsize=11)
        ax.set_xlabel("Gate value")
        ax.set_ylabel("Count")

    plt.suptitle("Gate Distributions for all λ values", fontsize=13)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    print(f"  Comparison plot saved → {save_path}")
    plt.show()



# Main


def main():
    # Force CPU if CUDA version is incompatible (e.g., P100 on old PyTorch)
    if torch.cuda.is_available():
        try:
            torch.zeros(1).cuda()          # quick smoke test
            device = torch.device("cuda")
        except Exception:
            print("CUDA unavailable (incompatible GPU) — falling back to CPU")
            device = torch.device("cpu")
    else:
        device = torch.device("cpu")

    print(f"Device: {device}\n")

    train_loader, test_loader = get_cifar10_loaders(batch_size=128)

    # Three λ values covering low / medium / high sparsity pressure
    lambdas = [1e-3, 1e-2, 1e-1]

    results   = []
    best_model = best_lambda = None
    best_score = -1e9

    for lam in lambdas:
        acc, sparsity, model = train_and_evaluate(
            lambda_sparse  = lam,
            train_loader   = train_loader,
            test_loader    = test_loader,
            device         = device,
            num_epochs     = 60,
            warmup_epochs  = 10,
        )
        results.append((lam, acc, sparsity, model))

        score = acc - 0.1 * sparsity
        if score > best_score:
            best_score = score
            best_model = model
            best_lambda = lam

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n\n" + "=" * 55)
    print("  RESULTS SUMMARY")
    print("=" * 55)
    print(f"{'Lambda':>10}  {'Test Accuracy':>14}  {'Sparsity (%)':>13}")
    print("-" * 45)
    for lam, acc, sparsity, _ in results:
        print(f"{lam:>10.1e}  {acc:>13.2f}%  {sparsity:>12.1f}%")
    print("=" * 55)

    # ── Markdown table ────────────────────────────────────────────────────────
    print("\n\n| Lambda | Test Accuracy (%) | Sparsity Level (%) |")
    print("|--------|-------------------|--------------------|")
    for lam, acc, sparsity, _ in results:
        print(f"| {lam:.1e} | {acc:.2f}             | {sparsity:.1f}               |")

    # Plots ─────────────────────────────────────────────────────────────────
    plot_gate_distribution(best_model, best_lambda, "gate_distribution_best.png")
    plot_all_distributions(results, "all_gate_distributions.png")


if __name__ == "__main__":
    main()